name: Simple python workflow

on: [push]

jobs:
  build:
    name: Build job
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install python3
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements-dev.txt
      - name: Style
        run: flake8 .

      - name: Type
        run: mypy workout_manager.py --disallow-untyped-defs

      - name: Test
        run: python -m pytest --junitxml=junit/test-results.xml --cov=app --cov-report=xml --cov-report=html
